### ISSUE TITLE
New version notifications not working on docker instances

### ISSUE THREAD

**Issue by jaymeswhyte** [jaymeswhyte/teemarr#25]
No update message and config.txt not updated

**Comment by jaymeswhyte** [comment]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/discord/client.py", line 449, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 89, in on_ready
    statusChannel = discord.utils.get(GUILD.channels, name="status")
AttributeError: 'Object' object has no attribute 'channels'
